plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'git-version-plugin'
}

android {
    compileSdk 31
    namespace "serial.android"

    sourceSets {
        main {
            jni.srcDirs = [] //disable automatic ndk-build call
        }
    }

    defaultConfig {
        minSdk 21
        //noinspection ExpiredTargetSdkVersion
        targetSdk 29
        versionName = gitVersionInfo.versionName
        versionCode = gitVersionInfo.versionCode

        buildConfigField "String", "VERSION", "\"${gitVersionInfo.versionName}\""
        buildConfigField "String", "REVISION", "\"${gitVersionInfo.revision}\""
        println("VERSION_NAME = $versionName, VERSION_CODE = $versionCode, REVISION = ${gitVersionInfo.revision}")

        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }

        // Similar to other properties in the defaultConfig block,
        // you can configure the ndk block for each product flavor
        // in your build configuration.
        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            // abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            jniDebuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    publishing {
        singleVariant('release') {
            withSourcesJar()
            withJavadocJar()
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.10.2"
        }
    }
}

afterEvaluate {
    publishing {
        repositories {
            maven {
                url 'https://fgbtfs.pkgs.visualstudio.com/Android/_packaging/Android-Integration/maven/v1'
                name 'azure'
                credentials(PasswordCredentials)
            }
        }
        publications {
            libserial(MavenPublication) {
                from components.release

                groupId = 'com.fortressgb'
                version = gitVersionInfo.versionName
                artifactId = project.name
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
}

//apply from: '../gradle-maven-push.gradle'